# 基础镜像
FROM node:18-alpine as builder

# 设置工作目录
WORKDIR /app

# 拷贝项目
COPY . .

# 安装依赖
RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install

# 构建前端（portal + dashboard）
RUN pnpm --filter portal build
RUN pnpm --filter dashboard build

# 第二阶段，用 nginx 作为静态服务
FROM nginx:alpine

# 将主应用、子应用复制到 nginx 的默认目录
COPY --from=builder /app/apps/portal/dist /usr/share/nginx/html/portal
COPY --from=builder /app/apps/dashboard/dist /usr/share/nginx/html/dashboard

# 用你自己的 nginx.conf（可选）
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
