# docker/Dockerfile.frontend
FROM nginx:alpine

# 直接 COPY 构建产物（你已经在 CI 构建完）
COPY docker/nginx.dashboard.conf /etc/nginx/conf.d/default.conf
COPY apps/dashboard/dist /usr/share/nginx/html/dashboard

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
