server {
  listen 80;

  # 默认访问 /portal/index.html
  location / {
    root /usr/share/nginx/html/portal;
    index index.html;
    try_files $uri /index.html;
  }

  # dashboard 子应用保持路径
  location /dashboard {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /dashboard/index.html;
  }
}
